let cart = JSON.parse(localStorage.getItem("canteenCart") || "[]");

const MENU_SESSIONS = {
  breakfast:{start:7,end:11,title:"Breakfast Menu",icon:"🌅",message:"Good morning! Breakfast items are available now."},
  lunch:{start:11,end:16,title:"Lunch Menu",icon:"☀️",message:"Lunch is being served now. Lunch Thali is available."},
  snacks:{start:16,end:19,title:"Snacks Menu",icon:"🍿",message:"Snack time! Grab something quick and tasty."},
  dinner:{start:19,end:21,title:"Dinner Menu",icon:"🌙",message:"Dinner is being served now. Dinner Thali is available."}
};
const PREP_TIMES = {"Vada Pav":4,"Samosa":3,"Masala Dosa":8,"Tea":3,"Cold Coffee":4,"Veg Sandwich":6,"Lunch Thali":10,"Dinner Thali":10};

function getCurrentSession(date=new Date()){const hour=date.getHours()+date.getMinutes()/60;for(const [key,s] of Object.entries(MENU_SESSIONS))if(hour>=s.start&&hour<s.end)return key;return null;}
function formatTime(date=new Date()){return date.toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"});}
function formatHour(hour){const suffix=hour>=12?"PM":"AM";const h=hour%12||12;return `${h}:00 ${suffix}`;}
function updateLiveClock(){const now=new Date();const clock=document.getElementById("liveClock"),date=document.getElementById("liveDate");if(clock)clock.textContent=now.toLocaleTimeString([], {hour:"2-digit",minute:"2-digit",second:"2-digit"});if(date)date.textContent=now.toLocaleDateString([], {weekday:"long",day:"numeric",month:"short",year:"numeric"});const session=getCurrentSession(now),status=document.getElementById("dashboardCanteenStatus"),dash=document.getElementById("dashboardSession");if(status){status.textContent=session?"● OPEN":"● CLOSED";status.className=session?"open-text":"closed-text";}if(dash)dash.textContent=session?`${MENU_SESSIONS[session].title} · ${formatHour(MENU_SESSIONS[session].start)} – ${formatHour(MENU_SESSIONS[session].end)}`:"Service closed · Next opening starts at 7:00 AM";}
function updateMenuByTime(){const now=new Date(),session=getCurrentSession(now),config=session?MENU_SESSIONS[session]:null,card=document.getElementById("menuSessionCard"),title=document.getElementById("sessionTitle"),message=document.getElementById("sessionMessage"),icon=document.getElementById("sessionIcon"),status=document.getElementById("sessionStatus"),time=document.getElementById("sessionTime"),noMenu=document.getElementById("noMenu");if(time)time.textContent=`Current time: ${formatTime(now)}`;if(!card||!title||!message||!icon||!status)return;card.classList.toggle("closed",!session);if(session){title.textContent=config.title;message.textContent=config.message;icon.textContent=config.icon;status.textContent="● OPEN";status.className="session-status open";if(noMenu)noMenu.hidden=true;}else{title.textContent="Canteen Closed";message.textContent="The canteen is closed right now. Service runs from 7:00 AM to 9:00 PM.";icon.textContent="🌙";status.textContent="● CLOSED";status.className="session-status closed-status";if(noMenu)noMenu.hidden=false;}applySessionFilter(session);}
function updateCartUI(){const count=cart.reduce((s,i)=>s+i.qty,0),total=cart.reduce((s,i)=>s+i.price*i.qty,0);const countEl=document.getElementById("cartCount"),totalEl=document.getElementById("cartTotal");if(countEl)countEl.textContent=`${count} item${count===1?"":"s"}`;if(totalEl)totalEl.textContent=`Cart total: ₹${total}`;localStorage.setItem("canteenCart",JSON.stringify(cart));}

document.querySelectorAll(".add-cart").forEach(button=>button.addEventListener("click",()=>{if(!getCurrentSession()){alert("The canteen is currently closed.");return;}const item=button.dataset.item,price=Number(button.dataset.price),existing=cart.find(x=>x.item===item);if(existing)existing.qty+=1;else cart.push({item,price,qty:1});updateCartUI();button.textContent="Added ✓";setTimeout(()=>button.textContent="Add",700);}));

function getOrders(){return JSON.parse(localStorage.getItem("canteenOrders")||"[]");}
function saveOrders(orders){localStorage.setItem("canteenOrders",JSON.stringify(orders));}
function getUser(){return JSON.parse(localStorage.getItem("canteenUser")||"null");}
function createToken(user,orders){const base=(user?.name||user?.username||"STU").replace(/[^a-zA-Z]/g,"").toUpperCase().slice(0,3).padEnd(3,"X");let token="",attempt=0;do{token=`${base}-${Math.floor(100+Math.random()*900)}`;attempt++;}while(orders.some(o=>o.token===token)&&attempt<30);return token;}
function estimateWait(orders,cartItems){const active=orders.filter(o=>["Pending","Preparing"].includes(o.status));const prep=Math.max(...cartItems.map(i=>PREP_TIMES[i.item]||5),5);const queueDelay=active.length*3;return Math.min(35,Math.max(5,prep+queueDelay));}

const checkoutBtn=document.getElementById("checkoutBtn");
if(checkoutBtn)checkoutBtn.addEventListener("click",()=>{if(!cart.length){alert("Your cart is empty. Add something from the menu first.");return;}if(!getCurrentSession()){alert("The canteen is currently closed.");return;}const user=getUser();if(!user||user.role!=="student"){alert("Please login as a student before ordering.");return;}const orders=getOrders(),total=cart.reduce((s,x)=>s+x.price*x.qty,0),estimatedMinutes=estimateWait(orders,cart),token=createToken(user,orders),now=Date.now();const order={id:`ORD-${now}`,token,student:user.name||user.username,studentUsername:user.username,items:cart.map(x=>({...x})),total,status:"Pending",createdAt:now,estimatedMinutes,eta:now+estimatedMinutes*60000};orders.push(order);saveOrders(orders);localStorage.setItem("lastStudentOrder",JSON.stringify(order));if(typeof addNotification==='function')addNotification({role:"staff",type:"new-order",title:"New food order received",message:`${order.student} placed ${order.items.reduce((s,i)=>s+i.qty,0)} item(s). Token ${order.token} · ETA ${estimatedMinutes} min.`,token});cart=[];updateCartUI();alert(`Order placed!\n\nYour personal token: ${token}\nEstimated wait: about ${estimatedMinutes} minutes\n\nYou'll be notified when it is ready.`);window.location.href="student-orders.html";});

const search=document.getElementById("menuSearch"),cards=[...document.querySelectorAll(".food-card")],categoryButtons=[...document.querySelectorAll(".category")];
function applySessionFilter(session=getCurrentSession()){cards.forEach(card=>{const sessions=(card.dataset.session||"").split(",");card.dataset.timeAvailable=Boolean(session&&sessions.includes(session));});filterMenu();}
function filterMenu(){const term=(search?.value||"").toLowerCase(),category=document.querySelector(".category.active")?.dataset.category||"all",session=getCurrentSession();let visible=0;cards.forEach(card=>{const sessions=(card.dataset.session||"").split(","),available=Boolean(session&&sessions.includes(session)),show=available&&card.dataset.name.includes(term)&&(category==="all"||card.dataset.category===category);card.style.display=show?"":"none";if(show)visible++;});const noResults=document.getElementById("noResults");if(noResults)noResults.hidden=!session||visible>0;}
search?.addEventListener("input",filterMenu);categoryButtons.forEach(btn=>btn.addEventListener("click",()=>{categoryButtons.forEach(x=>x.classList.remove("active"));btn.classList.add("active");filterMenu();}));
updateCartUI();updateLiveClock();updateMenuByTime();setInterval(()=>{updateLiveClock();updateMenuByTime();},1000);
