function staffOrders(){return JSON.parse(localStorage.getItem('canteenOrders')||'[]');}
function saveStaffOrders(orders){localStorage.setItem('canteenOrders',JSON.stringify(orders));}
function minutesLeft(order){if(order.status==='Ready')return 0;if(order.status==='Completed')return 0;return Math.max(1,Math.ceil((Number(order.eta||Date.now())-Date.now())/60000));}
function statusClass(status){return ({Pending:'pending',Preparing:'preparing',Ready:'ready',Completed:'completed'})[status]||'pending';}
function renderStaffOrders(){const list=document.getElementById('staffOrderList'),empty=document.getElementById('emptyOrders');if(!list)return;const orders=staffOrders().slice().sort((a,b)=>b.createdAt-a.createdAt);const active=orders.filter(o=>o.status!=='Completed');document.getElementById('newOrderCount').textContent=active.length;document.getElementById('pendingCount').textContent=orders.filter(o=>o.status==='Pending').length;document.getElementById('preparingCount').textContent=orders.filter(o=>o.status==='Preparing').length;document.getElementById('readyCount').textContent=orders.filter(o=>o.status==='Ready').length;empty.hidden=orders.length>0;list.innerHTML=orders.map(order=>{const items=order.items.map(i=>`${escapeStaff(i.item)} × ${i.qty}`).join(', ');const wait=minutesLeft(order);return `<div class="staff-order-card"><div class="staff-order-main"><div class="token-block"><span>PERSONAL TOKEN</span><strong>${escapeStaff(order.token)}</strong></div><div class="student-block"><strong>${escapeStaff(order.student)}</strong><small>@${escapeStaff(order.studentUsername||'student')}</small></div><div class="items-block"><strong>${items}</strong><small>₹${order.total} · ${new Date(order.createdAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</small></div><div class="eta-block"><span>Estimated wait</span><strong>${order.status==='Ready'?'Ready for pickup':order.status==='Completed'?'Completed':`~${wait} min`}</strong></div><select class="status-select ${statusClass(order.status)}" data-order-id="${order.id}"><option ${order.status==='Pending'?'selected':''}>Pending</option><option ${order.status==='Preparing'?'selected':''}>Preparing</option><option ${order.status==='Ready'?'selected':''}>Ready</option><option ${order.status==='Completed'?'selected':''}>Completed</option></select></div></div>`;}).join('');document.querySelectorAll('.status-select').forEach(select=>select.addEventListener('change',()=>updateOrderStatus(select.dataset.orderId,select.value)));}
function updateOrderStatus(id,status){const orders=staffOrders(),order=orders.find(o=>o.id===id);if(!order)return;const previous=order.status;order.status=status;if(status==='Preparing'&&previous==='Pending'){const remaining=Math.max(3,Number(order.estimatedMinutes||8));order.eta=Date.now()+remaining*60000;}if(status==='Ready'){order.eta=Date.now();order.readyAt=Date.now();}saveStaffOrders(orders);if(status==='Ready'&&previous!=='Ready'&&typeof addNotification==='function'){addNotification({role:'student',username:order.studentUsername,type:'ready',title:'Your food is ready! 🍽️',message:`Token ${order.token} is ready to collect. Please collect your order from the canteen.`,token:order.token});}renderStaffOrders();}
function escapeStaff(value=''){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
window.refreshOrderUI=renderStaffOrders;
renderStaffOrders();setInterval(renderStaffOrders,15000);
