(function(){
const money=n=>'₹'+Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:2});
const orders=()=>JSON.parse(localStorage.getItem('canteenOrders')||'[]');
const staffKey='canteenStaffAccounts';
const stockKey='canteenStock';
const periodNames={day:'Today',week:'This Week',month:'This Month',sixmonths:'Last 6 Months',year:'This Year',all:'All Time'};
const periodSelect=document.getElementById('periodSelect');
function seed(){
 let staff=JSON.parse(localStorage.getItem(staffKey)||'null'); if(!staff){staff=[{name:'Canteen Staff',username:'staff',password:'staff123',active:true,role:'staff'}];localStorage.setItem(staffKey,JSON.stringify(staff));}
 let stock=JSON.parse(localStorage.getItem(stockKey)||'null'); if(!stock){stock=[{name:'Potatoes',qty:25,unit:'kg',min:8},{name:'Bread',qty:12,unit:'packets',min:5},{name:'Milk',qty:3,unit:'litres',min:5},{name:'Tea Powder',qty:1.5,unit:'kg',min:2},{name:'Onion',qty:18,unit:'kg',min:6},{name:'Cooking Oil',qty:8,unit:'litres',min:3}];localStorage.setItem(stockKey,JSON.stringify(stock));}
}
function periodStart(type){const d=new Date();d.setHours(0,0,0,0);if(type==='day')return d;if(type==='week'){const day=d.getDay()||7;d.setDate(d.getDate()-day+1);return d}if(type==='month'){d.setDate(1);return d}if(type==='sixmonths'){d.setMonth(d.getMonth()-5);d.setDate(1);return d}if(type==='year'){d.setMonth(0,1);return d}return new Date(0)}
function inPeriod(ts,type){return new Date(ts)>=periodStart(type)}
function renderAnalytics(){
 const type=periodSelect.value, all=orders(), period=all.filter(o=>inPeriod(o.createdAt||o.timestamp||Date.now(),type));
 const completed=period.filter(o=>['Completed','Collected'].includes(o.status));const cancelled=period.filter(o=>o.status==='Cancelled');
 const revenue=completed.reduce((s,o)=>s+Number(o.total||0),0);const itemCount=completed.reduce((s,o)=>s+(o.items||[]).reduce((a,i)=>a+Number(i.qty||i.quantity||1),0),0);
 document.getElementById('revenueValue').textContent=money(revenue);document.getElementById('orderValue').textContent=completed.length;document.getElementById('itemsValue').textContent=itemCount;document.getElementById('cancelValue').textContent=cancelled.length;document.getElementById('revenuePeriod').textContent=periodNames[type]||type;
 const food={};completed.forEach(o=>(o.items||[]).forEach(i=>{const name=i.name||i.title||'Unknown';const qty=Number(i.qty||i.quantity||1);const price=Number(i.price||0);if(!food[name])food[name]={qty:0,revenue:0};food[name].qty+=qty;food[name].revenue+=qty*price;}));
 const rows=Object.entries(food).sort((a,b)=>b[1].qty-a[1].qty);document.getElementById('foodTable').innerHTML=rows.length?`<table class="data-table"><thead><tr><th>Food Item</th><th>Times Ordered / Qty Sold</th><th>Revenue</th></tr></thead><tbody>${rows.map(([n,v])=>`<tr><td><strong>${esc(n)}</strong></td><td>${v.qty}</td><td>${money(v.revenue)}</td></tr>`).join('')}</tbody></table>`:'<div class="empty-state">No completed orders for this period.</div>';
 const labels=['Today','This Week','This Month','Last 6 Months','This Year','All Time'];const types=['day','week','month','sixmonths','year','all'];document.getElementById('revenueBreakdown').innerHTML=types.map((t,i)=>{const c=all.filter(o=>inPeriod(o.createdAt||Date.now(),t)&&['Completed','Collected'].includes(o.status));const r=c.reduce((s,o)=>s+Number(o.total||0),0);return `<div class="bar-row"><div class="bar-label"><span>${labels[i]}</span><strong>${money(r)}</strong></div><div class="bar-track"><div class="bar-fill" style="width:${Math.min(100,r/(Math.max(1,revenue))*100)}%"></div></div></div>`}).join('');
 const statuses=['Pending','Preparing','Ready','Completed','Cancelled'];const max=Math.max(1,...statuses.map(s=>all.filter(o=>o.status===s).length));document.getElementById('statusBreakdown').innerHTML=statuses.map(s=>{const c=all.filter(o=>o.status===s).length;return `<div class="bar-row"><div class="bar-label"><span>${s}</span><strong>${c}</strong></div><div class="bar-track"><div class="bar-fill" style="width:${c/max*100}%"></div></div></div>`}).join('');
}
function esc(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function renderStaff(){const list=JSON.parse(localStorage.getItem(staffKey)||'[]');document.getElementById('staffTable').innerHTML=`<table class="data-table"><thead><tr><th>Name</th><th>Username</th><th>Status</th><th>Actions</th></tr></thead><tbody>${list.map((s,i)=>`<tr><td>${esc(s.name)}</td><td>${esc(s.username)}</td><td><span class="pill ${s.active?'active':'inactive'}">${s.active?'Active':'Inactive'}</span></td><td><button class="action-btn" onclick="toggleStaff(${i})">${s.active?'Deactivate':'Activate'}</button><button class="action-btn danger" onclick="removeStaff(${i})">Remove</button></td></tr>`).join('')}</tbody></table>`}
function renderStock(){const list=JSON.parse(localStorage.getItem(stockKey)||'[]');document.getElementById('stockTable').innerHTML=`<table class="data-table"><thead><tr><th>Item</th><th>Quantity</th><th>Minimum</th><th>Status</th><th>Action</th></tr></thead><tbody>${list.map((s,i)=>{const low=Number(s.qty)<=Number(s.min);return `<tr><td><strong>${esc(s.name)}</strong></td><td>${s.qty} ${esc(s.unit)}</td><td>${s.min} ${esc(s.unit)}</td><td><span class="pill ${low?'warning':'active'}">${low?'Low Stock':'Good'}</span></td><td><button class="action-btn" onclick="editStock(${i})">Update</button><button class="action-btn danger" onclick="removeStock(${i})">Remove</button></td></tr>`}).join('')}</tbody></table>`}
function openModal(html){document.getElementById('modal').innerHTML=html;document.getElementById('modalBackdrop').classList.add('show')}
function closeModal(){document.getElementById('modalBackdrop').classList.remove('show')}
document.getElementById('modalBackdrop').addEventListener('click',e=>{if(e.target.id==='modalBackdrop')closeModal()});
document.getElementById('addStaffBtn').onclick=()=>openModal(`<h2>Add Staff Member</h2><label>Name</label><input id="mName" placeholder="Full name"><label>Username</label><input id="mUser" placeholder="staff username"><label>Password</label><input id="mPass" type="password" placeholder="Password"><div class="modal-actions"><button class="btn btn-outline" onclick="closeAdminModal()">Cancel</button><button class="btn btn-primary" onclick="saveNewStaff()">Create Staff</button></div>`);
document.getElementById('addStockBtn').onclick=()=>openModal(`<h2>Add Stock Item</h2><label>Item name</label><input id="sName" placeholder="e.g. Rice"><label>Quantity</label><input id="sQty" type="number" min="0"><label>Unit</label><input id="sUnit" placeholder="kg / litres / packets"><label>Minimum stock</label><input id="sMin" type="number" min="0"><div class="modal-actions"><button class="btn btn-outline" onclick="closeAdminModal()">Cancel</button><button class="btn btn-primary" onclick="saveNewStock()">Add Stock</button></div>`);
window.closeAdminModal=closeModal;
window.saveNewStaff=()=>{const name=mName.value.trim(),username=mUser.value.trim().toLowerCase(),password=mPass.value;if(!name||!username||!password)return alert('Fill all fields.');const a=JSON.parse(localStorage.getItem(staffKey)||'[]');if(a.some(x=>x.username===username)||username==='admin')return alert('Username already exists.');a.push({name,username,password,active:true,role:'staff'});localStorage.setItem(staffKey,JSON.stringify(a));closeModal();renderStaff()};
window.toggleStaff=i=>{const a=JSON.parse(localStorage.getItem(staffKey)||'[]');a[i].active=!a[i].active;localStorage.setItem(staffKey,JSON.stringify(a));renderStaff()};
window.removeStaff=i=>{const a=JSON.parse(localStorage.getItem(staffKey)||'[]');if(confirm(`Remove ${a[i].name}?`)){a.splice(i,1);localStorage.setItem(staffKey,JSON.stringify(a));renderStaff()}};
window.saveNewStock=()=>{const name=sName.value.trim(),qty=Number(sQty.value),unit=sUnit.value.trim()||'units',min=Number(sMin.value);if(!name||qty<0||min<0)return alert('Enter valid stock details.');const a=JSON.parse(localStorage.getItem(stockKey)||'[]');a.push({name,qty,unit,min});localStorage.setItem(stockKey,JSON.stringify(a));closeModal();renderStock()};
window.editStock=i=>{const a=JSON.parse(localStorage.getItem(stockKey)||'[]'),s=a[i];openModal(`<h2>Update ${esc(s.name)}</h2><label>Quantity</label><input id="eQty" type="number" min="0" value="${s.qty}"><label>Minimum stock</label><input id="eMin" type="number" min="0" value="${s.min}"><div class="modal-actions"><button class="btn btn-outline" onclick="closeAdminModal()">Cancel</button><button class="btn btn-primary" onclick="saveEditStock(${i})">Save</button></div>`)};
window.saveEditStock=i=>{const a=JSON.parse(localStorage.getItem(stockKey)||'[]');a[i].qty=Number(eQty.value);a[i].min=Number(eMin.value);localStorage.setItem(stockKey,JSON.stringify(a));closeModal();renderStock()};window.removeStock=i=>{const a=JSON.parse(localStorage.getItem(stockKey)||'[]');if(confirm(`Remove ${a[i].name}?`)){a.splice(i,1);localStorage.setItem(stockKey,JSON.stringify(a));renderStock()}};
periodSelect.addEventListener('change',renderAnalytics);window.addEventListener('storage',e=>{if(['canteenOrders','canteenStaffAccounts','canteenStock'].includes(e.key)){renderAnalytics();renderStaff();renderStock()}});seed();renderAnalytics();renderStaff();renderStock();
})();
